# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddFilter.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(988, 277)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setMinimumSize(QtCore.QSize(40, 0))
        self.label.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_group = QtWidgets.QLineEdit(Form)
        self.lineEdit_group.setObjectName("lineEdit_group")
        self.horizontalLayout.addWidget(self.lineEdit_group)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_fore_color = QtWidgets.QPushButton(Form)
        self.pushButton_fore_color.setObjectName("pushButton_fore_color")
        self.horizontalLayout.addWidget(self.pushButton_fore_color)
        self.pushButton_back_color = QtWidgets.QPushButton(Form)
        self.pushButton_back_color.setObjectName("pushButton_back_color")
        self.horizontalLayout.addWidget(self.pushButton_back_color)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setMinimumSize(QtCore.QSize(40, 0))
        self.label_2.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBox_filter_history = QtWidgets.QComboBox(Form)
        self.comboBox_filter_history.setObjectName("comboBox_filter_history")
        self.horizontalLayout_2.addWidget(self.comboBox_filter_history)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.checkBox_excluding = QtWidgets.QCheckBox(Form)
        self.checkBox_excluding.setMinimumSize(QtCore.QSize(60, 0))
        self.checkBox_excluding.setMaximumSize(QtCore.QSize(120, 16777215))
        self.checkBox_excluding.setObjectName("checkBox_excluding")
        self.horizontalLayout_3.addWidget(self.checkBox_excluding)
        self.checkBox_case = QtWidgets.QCheckBox(Form)
        self.checkBox_case.setMinimumSize(QtCore.QSize(60, 0))
        self.checkBox_case.setMaximumSize(QtCore.QSize(120, 16777215))
        self.checkBox_case.setObjectName("checkBox_case")
        self.horizontalLayout_3.addWidget(self.checkBox_case)
        self.checkBox_regex = QtWidgets.QCheckBox(Form)
        self.checkBox_regex.setMinimumSize(QtCore.QSize(60, 0))
        self.checkBox_regex.setObjectName("checkBox_regex")
        self.horizontalLayout_3.addWidget(self.checkBox_regex)
        self.buttonBox_accept = QtWidgets.QDialogButtonBox(Form)
        self.buttonBox_accept.setMaximumSize(QtCore.QSize(200, 16777215))
        self.buttonBox_accept.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_accept.setObjectName("buttonBox_accept")
        self.horizontalLayout_3.addWidget(self.buttonBox_accept)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.plainTextEdit_description = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit_description.setObjectName("plainTextEdit_description")
        self.verticalLayout.addWidget(self.plainTextEdit_description)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.lineEdit_group, self.pushButton_fore_color)
        Form.setTabOrder(self.pushButton_fore_color, self.pushButton_back_color)
        Form.setTabOrder(self.pushButton_back_color, self.comboBox_filter_history)
        Form.setTabOrder(self.comboBox_filter_history, self.checkBox_excluding)
        Form.setTabOrder(self.checkBox_excluding, self.checkBox_case)
        Form.setTabOrder(self.checkBox_case, self.checkBox_regex)
        Form.setTabOrder(self.checkBox_regex, self.plainTextEdit_description)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Parent:"))
        self.lineEdit_group.setPlaceholderText(_translate("Form", "Set filter group here (Optional)"))
        self.pushButton_fore_color.setText(_translate("Form", "&Fore Color"))
        self.pushButton_back_color.setText(_translate("Form", "&Back Color"))
        self.label_2.setText(_translate("Form", "Filter: "))
        self.checkBox_excluding.setText(_translate("Form", "E&xcluding"))
        self.checkBox_case.setText(_translate("Form", "C&ase"))
        self.checkBox_regex.setText(_translate("Form", "&Regex"))
